apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ytop-chart.fullname" . }}-webhook-cert
  labels:
  {{- include "ytop-chart.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "ytop-chart.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "ytop-chart.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{
    .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: '{{ .Values.issuerRef.kind }}'
    name: '{{ include "ytop-chart.issuerRefName" . }}'
  secretName: yt-operator-webhook-cert