# permissions for end users to view remoteexecnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteexecnodes-viewer-role
rules:
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes/status
  verbs:
  - get
