---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulset
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulset/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - chyts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - chyts/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - chyts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteexecnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteytsaurus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteytsaurus/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - remoteytsaurus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - ytsaurus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - ytsaurus/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - ytsaurus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pod/status
  verbs:
  - get
