apiVersion: cluster.ytsaurus.tech/v1
kind: Ytsaurus
metadata:
  name: minisaurus
spec:
  coreImage: ytsaurus/ytsaurus:unstable-0.0.4
  uiImage: ytsaurus/ui:stable

  discovery:
    instanceCount: 1

  primaryMasters:
    instanceCount: 1
    cellTag: 1
    locations:
      - locationType: MasterChangelogs
        path: /yt/master-data/master-changelogs
      - locationType: MasterSnapshots
        path: /yt/master-data/master-snapshots

    volumeMounts:
      - name: master-data
        mountPath: /yt/master-data

    volumeClaimTemplates:
      - metadata:
          name: master-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi

  httpProxies:
    - serviceType: NodePort
      instanceCount: 1
      role: default
    - serviceType: NodePort
      instanceCount: 1
      role: control

  rpcProxies:
    - instanceCount: 1
      role: default
    - instanceCount: 1
      role: heavy

  dataNodes:
    - instanceCount: 1

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      locations:
        - locationType: ChunkStore
          path: /yt/node-data/chunk-store

      volumeClaimTemplates:
        - metadata:
            name: node-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 5Gi

  execNodes:
    - instanceCount: 1

      resources:
        limits:
          cpu: 1
          memory: 2Gi

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      volumes:
        - name: node-data
          emptyDir:
            sizeLimit: 5Gi

      locations:
        - locationType: ChunkCache
          path: /yt/node-data/chunk-cache
        - locationType: Slots
          path: /yt/node-data/slots

  schedulers:
    instanceCount: 1

  controllerAgents:
    instanceCount: 1

  ui:
    serviceType: NodePort
    instanceCount: 1
