apiVersion: cluster.ytsaurus.tech/v1
kind: RemoteYtsaurus
metadata:
  name: remote-ytsaurus
spec:
  cellTag: 1
  # FIXME: Must be optional.
  cellTagMasterCaches: 1
  # FIXME Lookup master endpoints via service.
  hostAddresses:
    - ms-0.masters.ytsaurus.svc
