# https://kind.sigs.k8s.io/docs/user/configuration/

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# overriden by environment KIND_CLUSTER_NAME
name: kind

# https://kind.sigs.k8s.io/docs/user/configuration/#networking
networking:
# ipFamily: dual
# ipFamily: ipv6
# podSubnet: "10.244.0.0/16"
# serviceSubnet: "10.96.0.0/12"
# disableDefaultCNI: true
# kubeProxyMode: "ipvs"
# kubeProxyMode: "none"

runtimeConfig:
# "api/alpha": "true"

# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
featureGates:
# "KubeletCgroupDriverFromCRI": true
# "NewVolumeManagerReconstruction": true
# "InPlacePodVerticalScaling": true
# "MemoryQoS": true
# "CustomCPUCFSQuotaPeriod": true
# "StatefulSetStartOrdinal": true
# "StatefulSetAutoDeletePVC": true

# https://kind.sigs.k8s.io/docs/user/local-registry/
# https://github.com/containerd/containerd/blob/main/docs/hosts.md
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"

# https://kind.sigs.k8s.io/docs/user/configuration/#nodes
nodes:
- role: control-plane
  # https://kind.sigs.k8s.io/docs/user/configuration#kubeadm-config-patches
  # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#etcd-flags
  # https://etcd.io/docs/v3.5/op-guide/configuration/#command-line-flags
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    etcd:
      local:
        extraArgs:
          unsafe-no-fsync: "true"
  extraMounts:
  - &registry-config
    hostPath: "config/registry"
    containerPath: "/etc/containerd/certs.d"
    readOnly: true
- role: worker
  extraMounts:
  - *registry-config
- role: worker
  extraMounts:
  - *registry-config
- role: worker
  extraMounts:
  - *registry-config
