apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: any
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ include "${name}.fullname" . }}-webhook-cert'
