apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: any
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: '{{ include "${name}.fullname" . }}-webhook-service'
          namespace: '{{ .Release.Namespace }}'
          path: /convert
      conversionReviewVersions:
      - v1
