name: Build and test

on:
  pull_request:

jobs:
  e2e:
    name: Run e2e test on KinD
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Build
        shell: bash
        run: |
          make build

      - name: Run tests
        shell: bash
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --retain -v 100
          kubectl get pod

          make k8s-install-cert-manager
          make helm-kind-install
          make kind-load-test-images
          YTSAURUS_ENABLE_E2E_TESTS=true make test
          helm uninstall ytsaurus

          ./compat_test.sh --from-version 0.4.1 --to-version trunk
