name: Build and test

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Run checks
    with:
      release: true
    secrets:
      DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    uses: ./.github/workflows/subflow_run_e2e.yaml

  send-notifications:
    name: Send notifications
    needs:
      - check
    runs-on: trampoline
    if: ${{ failure() }}
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Workflow *${{github.workflow}}* failed: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.
            Commit: ${{github.event.head_commit.sha}}
            Message:
            ```
            ${{github.event.head_commit.message}}
            ```
