name: Build and test

on:
  pull_request:

jobs:
  e2e:
    name: Run e2e test on KinD
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          cluster_name: kind

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Build
        shell: bash
        run: |
          make build

      - name: Run tests
        shell: bash
        run: |
          kubectl get pod
          make k8s-install-cert-manager
          make helm-kind-install
          make kind-load-test-images
          YTSAURUS_ENABLE_E2E_TESTS=true make test
          kubectl get pod -A
          kubectl logs 
          helm uninstall ytsaurus

          ./compat_test.sh --from-version 0.4.1 --to-version trunk
