name: PR notifications

on:
  pull_request_target:
    branches:
      - main
    types:
      - review_requested
      - ready_for_review

jobs:
  pr-notifications:
    name: Send PR notifications
    runs-on: trampoline
    steps:
      - name: Send to notification chat
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFICATIONS_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            New PR in *${{ github.repository }}*: `${{ github.event.pull_request.title }}`
            ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}

      - name: Send to k8s operator chat
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_K8S_OPERATOR_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            New PR in *${{ github.repository }}*: `${{ github.event.pull_request.title }}`
            ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}

