on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
    secrets:
      DOCKER_HUB_LOGIN:
        required: false
      DOCKER_HUB_PASSWORD:
        required: false

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run linters
        shell: bash
        run: |
          make lint
          make lint-generated

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Build
        shell: bash
        run: |
          make build

      - name: Run tests
        shell: bash
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --retain -v 100
          kubectl get pod

          make k8s-install-cert-manager
          make helm-kind-install
          make kind-load-test-images
          make test
          make test-e2e
          helm uninstall ytsaurus

          ./compat_test.sh --from-version 0.4.1 --to-version trunk

      - name: Docker Hub login
        if: ${{ inputs.release }}
        run: |
          echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_HUB_LOGIN}} --password-stdin

      - name: Docker
        if: ${{ inputs.release }}
        shell: bash
        run: |
          make release RELEASE_VERSION=0.0.$(git rev-list --count HEAD)-dev-${GITHUB_SHA} OPERATOR_IMAGE=ytsaurus/k8s-operator-nightly OPERATOR_CHART=ytop-chart-nightly
